name: Erlang CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        otp: [23.3.1]
    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: ${{matrix.otp}}
    - name: Compile
      run: rebar3 compile
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run xref
      run: rebar3 xref
    - name: Run elvis
      run: rebar3 as lint lint
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghrc.io/widgrensit/chatli:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
